Source/Ui/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Ui.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(1024, MinimumLength = 5)]
        public string Message { get; set; }
    }
}

Source/Ui/Controllers/Web/AppController.cs
using Microsoft.AspNet.Mvc;

namespace Ui.Controllers.Web
{
    public class AppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
    }
}

Source/Ui/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}
<h2>About The World</h2>

Source/Ui/Views/App/Contact.cshtml
@model Ui.ViewModels.ContactViewModel

@{
    ViewBag.Title = "Contact Us";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<h2>Contact</h2>

<form method="post">
    @if (ViewBag.Message != null)
    {
        <div>@ViewBag.Message</div>
    }
    <div></div>
    <label asp-for="Name">Name</label>
    <input asp-for="Name"/>
    <span></span>

    <label asp-for="Email">Email</label>
    <input type="email" asp-for="Email"/>
    <span></span>

    <label asp-for="Message">Message</label>
    <textarea cols="40" rows="4" asp-for="Message"></textarea>
    <span></span>

    <div>
        <input type="submit" value="Send Message"/>
    </div>
</form>

Source/Ui/Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h1>The World</h1>
<p>This will be a fun website soon!</p>

<form>
    <div>
        <label>Date</label>
        <input />
    </div>
    <div>
        <label>Location</label>
        <input />
    </div>
    <div><input type="submit" value="Add" /></div>
</form>

Source/Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/css/site.css" />

</head>

<body>

    <div id="sidebar">
        <img src="~/img/user1.png" alt="headshot" class="headshot" />
        <span id="username">Magic</span>
        <ul class="menu">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        </ul>
    </div>

    <div id="wrapper">
        <div id="main">
            <div>
                <button id="sidebarToggle">Toggle Menu</button>
            </div>

            <div>
                @RenderBody()
            </div>

        </div>
        <div id="footer">
            &copy; 2015 The World Ltd.
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>

    @RenderSection("Scripts", false)

</body>

</html>